/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.nprog.forme;



import java.util.ArrayList;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import rs.ac.bg.fon.nprog.domen.OpstiDomenskiObjekat;
import rs.ac.bg.fon.nprog.domen.Trener;
import rs.ac.bg.fon.nprog.server.PokretanjeServeraNit;


/**
 *
 * @author HP
 */
public class ServerskaForma extends javax.swing.JFrame {

    /**
     * Creates new form ServerskaForma
     */
    
    PokretanjeServeraNit psn;
    List<Trener> povezani;
    
    public ServerskaForma() {
        initComponents();
        srediFormu();
        povezani=new ArrayList<>();
        /*jLabel1.setIcon(new javax.swing.ImageIcon("resources/logo.png"));
        jLabel1.setBounds(30, 30, 30, 30);
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelaPokreni = new javax.swing.JLabel();
        btnPokreniZaustavi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        povezaniMeni = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Serverska Forma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        labelaPokreni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelaPokreni.setText("Poruka za server");

        btnPokreniZaustavi.setBackground(new java.awt.Color(153, 153, 153));
        btnPokreniZaustavi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPokreniZaustavi.setForeground(new java.awt.Color(204, 0, 0));
        btnPokreniZaustavi.setText("Pokreni server");
        btnPokreniZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniZaustaviActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Documents\\NetBeansProjects\\KaratePSServer\\resources\\logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelaPokreni, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnPokreniZaustavi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreniZaustavi)
                    .addComponent(labelaPokreni))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        povezaniMeni.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        povezaniMeni.setText("Povezani");
        povezaniMeni.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuBar2.add(povezaniMeni);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniZaustaviActionPerformed
        if(!PokretanjeServeraNit.isRadi()){
            psn = new PokretanjeServeraNit(this);
            psn.start();
            PokretanjeServeraNit.setRadi(true);
            serverPokrenut();
        }else{
            psn.zaustaviNiti();
            serverNijePokrenut();
            PokretanjeServeraNit.setRadi(false);
        }
    }//GEN-LAST:event_btnPokreniZaustaviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniZaustavi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelaPokreni;
    private javax.swing.JMenu povezaniMeni;
    // End of variables declaration//GEN-END:variables

     private void serverPokrenut() {
        btnPokreniZaustavi.setText("Zaustavite server");
        labelaPokreni.setText("Server je pokrenut");
        
       
    }

    private void serverNijePokrenut() {
        btnPokreniZaustavi.setText("Pokrenite server");
        labelaPokreni.setText("Server nije pokrenut");
    }

    private void srediFormu() {
        this.setTitle("Server program");
        btnPokreniZaustavi.setText("Pokrenite server");
        labelaPokreni.setText("Server nije pokrenut");
        
    }
    
    public void ubaciUlogovanog(OpstiDomenskiObjekat odo){
        Trener t=(Trener) odo;
        povezani.add(t);
        postaviMeni();
    }
        
    public void izbaciUlogovanog(OpstiDomenskiObjekat odo){
        Trener t=(Trener) odo;
        for (Trener trener : povezani) {
            if(trener.getTrenerID()==t.getTrenerID()){
                povezani.remove(trener);
                postaviMeni();
                return;
            }
        }
    }

    private void postaviMeni() {
        povezaniMeni.removeAll();
        for(Trener t: povezani){
            String imePrez=t.getIme()+" "+t.getPrezime();
            JMenuItem te=new JMenuItem(imePrez);
            povezaniMeni.add(te);
        }
    }
    
    
}
