/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.nprog.forme.trening;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;

import rs.ac.bg.fon.nprog.domen.Grupa;
import rs.ac.bg.fon.nprog.domen.OpstiDomenskiObjekat;
import rs.ac.bg.fon.nprog.domen.Sala;
import rs.ac.bg.fon.nprog.domen.Trener;
import rs.ac.bg.fon.nprog.domen.Trening;
import rs.ac.bg.fon.nprog.domen.Vezba;
import rs.ac.bg.fon.nprog.exception.ValidacijaException;
import rs.ac.bg.fon.nprog.kontroler.Kontroler;
import rs.ac.bg.fon.nprog.modeli.ModelTabeleStavka;
import rs.ac.bg.fon.nprog.modeli.ModelTabeleVezba;

import java.util.Calendar;

/**
 *
 * @author HP
 */

public class DodajTrening extends javax.swing.JFrame {

    /**
     * Creates new form DodajTrening
     */
    
    
    JFrame glavna;
    String status;
    ModelTabeleStavka mts;
    Trening trening;
    ModelTabeleVezba mtv;
    JFrame glavnaForma;
    
    
    public DodajTrening() {
        initComponents();
    }

    public DodajTrening(JFrame glavna,Trener trener) {
        initComponents();
        this.glavna = glavna;
        this.setTitle("Unos treninga");
        ButtonGroup grupa = new ButtonGroup();
        grupa.add(rblako);
        grupa.add(rbsrednje);
        grupa.add(rbtesko);
        this.glavnaForma = glavna;
        //trening =new Trening(0, "", null, 0, trener, null, null);
        trening=new Trening(0);
        trening.setTrener(trener);
        txtTrajanje.setText(String.valueOf(trening.getTrajanje()));
        popuniTabeluVezbe();
        this.status = "unos";
        popuniCBGrupe();
        popuniCBSale();
        srediFormu();
        srediTabelu();
    }

    public DodajTrening(PretragaTrening pretraga, Trening izabrani) {
        initComponents();
        this.setTitle("Izmena treninga");
        this.glavnaForma = pretraga;
        ButtonGroup grupa = new ButtonGroup();
        grupa.add(rblako);
        grupa.add(rbsrednje);
        grupa.add(rbtesko);
        trening =izabrani;
        txtTrajanje.setText(String.valueOf(trening.getTrajanje()));
        this.status = "izmena";
        popuniTabeluVezbe();
        popuniCBGrupe();
        popuniCBSale();
        srediFormu();
        
        srediTabeluZaIzmenu();
        srediZaIzmenuSve();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVezba = new javax.swing.JTable();
        rbtesko = new javax.swing.JRadioButton();
        rbsrednje = new javax.swing.JRadioButton();
        rblako = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBrojPonavljanja = new javax.swing.JTextField();
        btnDodajVezbu = new javax.swing.JButton();
        labelaTezina = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaStavka = new javax.swing.JTable();
        btnObrisiStavku = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNazivTreninga = new javax.swing.JTextField();
        txtTrener = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbSala = new javax.swing.JComboBox();
        cbGrupa = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txtTreningID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTrajanje = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSacuvajTrening = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        datumOdabir = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        satiOdabir = new com.toedter.components.JSpinField();
        minutaOdabir = new com.toedter.components.JSpinField();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trening", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stavka Treninga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tabelaVezba.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelaVezba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaVezba);

        rbtesko.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtesko.setText(" Tesko");
        rbtesko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbteskoActionPerformed(evt);
            }
        });

        rbsrednje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbsrednje.setText(" Srednje");
        rbsrednje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsrednjeActionPerformed(evt);
            }
        });

        rblako.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rblako.setText(" Lako");
        rblako.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblakoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Težina");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Vežba");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Broj ponavljanja: ");

        txtBrojPonavljanja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnDodajVezbu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDodajVezbu.setText("Dodaj vežbu");
        btnDodajVezbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajVezbuActionPerformed(evt);
            }
        });

        labelaTezina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelaTezina.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(rbsrednje)
                            .addComponent(rblako)
                            .addComponent(rbtesko))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBrojPonavljanja, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDodajVezbu)))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(labelaTezina, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(8, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtBrojPonavljanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDodajVezbu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rblako)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbsrednje)
                        .addGap(10, 10, 10)
                        .addComponent(rbtesko)))
                .addComponent(labelaTezina, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelaStavka.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelaStavka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaStavka);

        btnObrisiStavku.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnObrisiStavku.setText("Obriši stavku");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Vreme početka :");

        txtNazivTreninga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtTrener.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Trener :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Naziv treninga :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Sala :");

        cbSala.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbGrupa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbGrupa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Grupa :");

        txtTreningID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Trening ID :");

        txtTrajanje.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Projektovano vreme trajanja treninga je :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("minuta");

        btnSacuvajTrening.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSacuvajTrening.setText("Sačuvaj trening");
        btnSacuvajTrening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajTreningActionPerformed(evt);
            }
        });

        btnOtkazi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnOtkazi.setText("Otkaži");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        datumOdabir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Datum:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("h");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("min");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnObrisiStavku))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSacuvajTrening)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(53, 53, 53)
                                            .addComponent(jLabel1))
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTreningID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNazivTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(datumOdabir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(satiOdabir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(minutaOdabir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTreningID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTrener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNazivTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(satiOdabir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(minutaOdabir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel5)))
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel7))
                                .addGap(31, 31, 31)
                                .addComponent(datumOdabir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(5, 5, 5)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSacuvajTrening, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOtkazi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbteskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbteskoActionPerformed
        labelaTezina.setText("Vežba se produžava 2 minuta");
    }//GEN-LAST:event_rbteskoActionPerformed

    private void rbsrednjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsrednjeActionPerformed
        labelaTezina.setText("Vežba ne menja dužinu");
    }//GEN-LAST:event_rbsrednjeActionPerformed

    private void rblakoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblakoActionPerformed
        labelaTezina.setText("Vežba kraća za 2 minuta");
    }//GEN-LAST:event_rblakoActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        dispose();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnDodajVezbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajVezbuActionPerformed
        int red = tabelaVezba.getSelectedRow();
        if (red != -1) {
            try {
                proveriZaStavku();
                Vezba v = (Vezba) mtv.getLista().get(red);
                if(rblako.isSelected()) mts.setTezina(rblako.getText().trim());
                if(rbsrednje.isSelected()) mts.setTezina(rbsrednje.getText().trim());
                if(rbtesko.isSelected()) mts.setTezina(rbtesko.getText().trim());
                mts.setBrojPonavljanja(Integer.parseInt(txtBrojPonavljanja.getText()));
                mts.dodajStavku(v, trening);
            } catch (ValidacijaException ex) {
                Logger.getLogger(DodajTrening.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
            }
            }
         else {
            JOptionPane.showMessageDialog(rootPane, "Izaberite vežbu koji želite da dodate!");
        }
    }//GEN-LAST:event_btnDodajVezbuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
        int red = tabelaStavka.getSelectedRow();
        if (red != -1) {
            mts.izbaciStavku(red);
            mts.postaviRB();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Izaberite stavku koju želite da izbacite!");
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void btnSacuvajTreningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajTreningActionPerformed
        try {
            if(txtNazivTreninga.getText().isEmpty()){
               throw new ValidacijaException("Sva polja su obavezna!");
            }
            
            if(!(String.valueOf(satiOdabir.getValue()).matches("^\\d{1,2}$"))){
                throw new ValidacijaException("Sati nisu u dobro uneti!");
            }
            
            if(!(String.valueOf(minutaOdabir.getValue()).matches("^\\d{1,2}$"))){
                throw new ValidacijaException("Minuti nisu u dobro uneti!");
            }
            
            datumOdabir.setDateFormatString("dd.MM.yyyy");
            String datumStr=proveriDatumIRadnoVreme(datumOdabir,satiOdabir.getValue(),minutaOdabir.getValue());
            String nazivTr=txtNazivTreninga.getText().trim();
            Grupa gr = (Grupa) cbGrupa.getSelectedItem();
            Sala sa=(Sala) cbSala.getSelectedItem();
            SimpleDateFormat sdf=new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
            Date datumVreme;
            try{
            String formatSat=vratiFormat(satiOdabir.getValue());
            String formatMinut=vratiFormat(minutaOdabir.getValue());
            datumVreme =sdf.parse(datumStr+" "+formatSat+":"+formatMinut+":00");
            }catch(ParseException ex){
                Logger.getLogger(DodajTrening.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"Neispravno konvertovanje u datum vreme","Greška",JOptionPane.ERROR_MESSAGE);
                return;
            }
            postaviIProveriVrednosti(gr,sa,datumVreme,nazivTr);
            Trening tre;
            if (status.equals("unos")) {
                tre = (Trening) Kontroler.vratiInstancu().sacuvajTrening(trening);
                JOptionPane.showMessageDialog(this, "Uspešno ste sačuvali trening.","Uspešno", JOptionPane.INFORMATION_MESSAGE);
            }else{
                tre = (Trening) Kontroler.vratiInstancu().izmeniTrening(trening);
                JOptionPane.showMessageDialog(this, "Uspešno ste izmenili trening.","Uspešno", JOptionPane.INFORMATION_MESSAGE);
            }
            glavnaForma.setVisible(true);
            dispose();
        } catch (ParseException ex) {
            Logger.getLogger(DodajTrening.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Neispravno unet datum","Greška",JOptionPane.ERROR_MESSAGE);
        } catch (ValidacijaException ex) {
            Logger.getLogger(DodajTrening.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(DodajTrening.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajTreningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DodajTrening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajVezbu;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnSacuvajTrening;
    private javax.swing.JComboBox cbGrupa;
    private javax.swing.JComboBox cbSala;
    private com.toedter.calendar.JDateChooser datumOdabir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelaTezina;
    private com.toedter.components.JSpinField minutaOdabir;
    private javax.swing.JRadioButton rblako;
    private javax.swing.JRadioButton rbsrednje;
    private javax.swing.JRadioButton rbtesko;
    private com.toedter.components.JSpinField satiOdabir;
    private javax.swing.JTable tabelaStavka;
    private javax.swing.JTable tabelaVezba;
    private javax.swing.JTextField txtBrojPonavljanja;
    private javax.swing.JTextField txtNazivTreninga;
    private javax.swing.JTextField txtTrajanje;
    private javax.swing.JTextField txtTrener;
    private javax.swing.JTextField txtTreningID;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluVezbe() {
        try {
            List<OpstiDomenskiObjekat> vezbe = Kontroler.vratiInstancu().vratiVezbe();
            mtv = new ModelTabeleVezba(vezbe);
            tabelaVezba.setModel(mtv);
        } catch (Exception ex) {
            Logger.getLogger(DodajTrening.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void popuniCBGrupe() {
        try {
            List<OpstiDomenskiObjekat> listaGrupa = Kontroler.vratiInstancu().vratiGrupe();
            cbGrupa.setModel(new DefaultComboBoxModel(listaGrupa.toArray()));
            cbGrupa.setSelectedItem(null);
        } catch (Exception ex) {
            Logger.getLogger(DodajTrening.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void popuniCBSale() {
        try {
            List<OpstiDomenskiObjekat> listaSala = Kontroler.vratiInstancu().vratiSale();
            cbSala.setModel(new DefaultComboBoxModel(listaSala.toArray()));
            cbSala.setSelectedItem(null);
        } catch (Exception ex) {
            Logger.getLogger(DodajTrening.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void srediFormu() {
        txtTreningID.setEnabled(false);
        txtTrener.setText(trening.getTrener().getIme()+" "+trening.getTrener().getPrezime());
        txtTrener.setEnabled(false);
        txtTrajanje.setEnabled(false);
    }

    private void srediTabelu() {
        mts = new ModelTabeleStavka();
        mts.setTxtTrajanje(txtTrajanje);
        tabelaStavka.setModel(mts);
    }

    private void proveriZaStavku() throws ValidacijaException {
        if(!rblako.isSelected() && !rbsrednje.isSelected() && !rbtesko.isSelected()){
            throw new ValidacijaException("Morate selektovati težinu!");
        }
        if(txtBrojPonavljanja.getText().isEmpty()){
            throw new ValidacijaException("Unesite broj ponavljanja!");
        }
        if(!txtBrojPonavljanja.getText().matches(("[1-9]|10"))){
            throw new ValidacijaException("Unesite broj ponavljanja [1-10]!");
        }
        
                
        
    }

    private void postaviIProveriVrednosti(Grupa grupa, Sala sala, Date datumVreme, String nazivTr) throws ValidacijaException {
        
        
        if(grupa==null){
            throw new ValidacijaException("Izaberi grupu!");
        }
        
        if(sala==null){
            throw new ValidacijaException("Izaberi salu");
        }
        
        if(!datumVreme.after(new Date())){
            throw new ValidacijaException("Datum i vreme je iz prošlosti (ili je trenutni datum i vreme)");
        }
        
        
        
        List<OpstiDomenskiObjekat> listaStavki = mts.getLista();
        
        if (listaStavki.isEmpty()) {
            throw new ValidacijaException("Morate uneti makar jednu stavku!");
        }
        
        trening.setDatumVreme(datumVreme);
        trening.setNaziv(nazivTr);
        trening.setGrupa(grupa);
        trening.setSala(sala);
        trening.setListaStavki((ArrayList<OpstiDomenskiObjekat>) listaStavki);
        trening.setTrajanje(Integer.parseInt(txtTrajanje.getText().trim()));
        
        
    }

    private String proveriDatumIRadnoVreme(JDateChooser jdc,int sati,int minuti) throws ValidacijaException {
        
        SimpleDateFormat sdf1= new SimpleDateFormat("dd.MM.yyyy");
        
        
        if(jdc.getDate()==null){
            throw new ValidacijaException("Datum nije dobro unet!");
        }
        
        String datumString=sdf1.format(jdc.getDate());
        
        
        if(!datumString.matches("\\d{2}\\.\\d{2}\\.\\d{4}")){
            throw new ValidacijaException("Datum nije dobro unet");
        }
        
        
        
        if(sati<9 || sati>21){
            throw new ValidacijaException("Sati radnog vremena (9-22h)!");
        }
        
        if(minuti<0 || minuti>60){
            throw new ValidacijaException("Nisu lepo uneti minuti");
        }
        
        if(!(txtNazivTreninga.getText().matches("^[A-Z].*"))){
            throw new ValidacijaException("Naziv treninga počinje velikim slovom");
        }
        
        return datumString;
    }

    private String vratiFormat(int value) {
        if(value<10){
            return "0"+value;
        }else{
            return value+"";
        }
    }

    private void srediZaIzmenuSve() {
        txtTreningID.setText(String.valueOf(trening.getTreningID()));
        txtNazivTreninga.setText(trening.getNaziv());
        datumOdabir.setDate(trening.getDatumVreme());
        Calendar pomocni=Calendar.getInstance();
        pomocni.setTime(trening.getDatumVreme());
        int sati = pomocni.get(Calendar.HOUR_OF_DAY);
        int minuta=pomocni.get(Calendar.MINUTE);
        
        satiOdabir.setValue(sati);
        minutaOdabir.setValue(minuta);
        
        cbSala.setSelectedItem(trening.getSala());
        cbGrupa.setSelectedItem(trening.getGrupa());
        
        
        
    }

    private void srediTabeluZaIzmenu() {
        mts = new ModelTabeleStavka(trening.getListaStavki());
        mts.setTxtTrajanje(txtTrajanje);
        tabelaStavka.setModel(mts);
    }
}
